image:
  file: .gitpod.Dockerfile
  
  
tasks:
  - init:     pip3 install jupyter pandas                               &&
              pip3 install matplotlib notebook ipywidgets rise 
    command: jupyter notebook --generate-config                         &&
             jupyter notebook --generate-config
